### ISSUE TITLE
just a suggestion

### ISSUE THREAD

**Issue by rcrooks** [imalbert/conifer-vscode-theme#5]
Hi @imalbert I think the variants you added are really great additions to a great theme!

I have just a small suggestion: make the bracket colors (I think that's punctuation) a little darker (or lighter) than the tag name.

Thanks for considering,
Robert

**Comment by imalbert** [comment]
Hi @rcrooks, I appreciate your feedback late as it is! I've put this on my list of improvements once I find some time to get back to working on this again.  Thank you for your patience 👍

**Comment by imalbert** [comment]
I published a new version today including your suggestion. Please check it out
